### ISSUE TITLE
Mailgun option not showing up

### ISSUE THREAD

**Issue by marcoelho97** [Bogardo/Mailgun-Magento2#2]
So, I have used the composer command and it has installed. Unfortunately, at the settings, I have no Mailgun option there, as you mention in the readme file...
Am I doing something wrong?
![image](https://cloud.githubusercontent.com/assets/13586621/17444110/2634e53c-5b36-11e6-8564-dd19e685e221.png)

**Comment by marcoelho97** [comment]
@Bogardo Could you tell me if I'm doing something wrong, please?

**Comment by Bogardo** [comment]
@marcoelho97 Have you cleared all caches?

**Comment by marcoelho97** [comment]
@Bogardo Yes, I have cleared all caches.

**Comment by rhertogh** [comment]
I had to run `php bin/magento setup:upgrade`

**Comment by makhnovskiy** [comment]
Awesome fix! Had to do the same.
