### ISSUE TITLE
'To' parameter is missing

### ISSUE THREAD

**Issue by ojhaujjwal** [Bogardo/Mailgun-Magento2#3]
Here is the screenshot:
![b24ceb3a-4928-4d84-8d47-c3a4f05ce358](https://cloud.githubusercontent.com/assets/4995501/17648057/55aee576-6228-11e6-9b0c-8f40c1bf8002.jpg)

Here is a look at the message headers:
![db71d523-abd2-4409-bbf9-b48a70203cff](https://cloud.githubusercontent.com/assets/4995501/17648075/bb076fe2-6228-11e6-95c4-877eaad7eb29.jpg)

You can see that the format of the header is like ['To' => ['Name name@email.com']]. So, it is not found in `recipients` array and hence To part is empty.

**Comment by zhipeng001** [comment]
Hi @Bogardo , thanks for your extension. It woks great. But I also found sometimes I encounter this problem when creating new users.

**Comment by benheart** [comment]
@Bogardo Thanks for your extension, but i think you should release a new version. If someone install version 0.1.4, the problem is still remain.

**Comment by unreal4u** [comment]
Hi, could you please release a new version, I just had this exact same problem when placing a new order which was solved by using dev-master which I think is not the intention. 

Thanks!
